/** Blog index (/blog)  -  SEO + hero copy */
export const BLOG_INDEX_SEO = {
  title: "Insights | AI, Security & Data Engineering Notes | AiRAT",
  description:
    "Long-form writing on production RAG, OpenSearch, SOC automation, data governance, GEO, and AI search visibility for technical leaders.",
} as const;

export const BLOG_INDEX_HERO = {
  eyebrow: "Intelligence from the field",
  title: "Notes on systems that have to work.",
  lead: "Depth-first writing on production RAG, search infrastructure, SOC operations, data governance, and AI-era visibility  -  held to the same standard as our delivery work.",
  subNote: "Written by engineers building these systems. Not summarised from press releases.",
} as const;

/** Editorial research cluster taxonomy  -  4 areas (Anthropic-style) */
export const BLOG_RESEARCH_CLUSTERS = [
  {
    id: "ai-llm",
    label: "AI Systems & LLM",
    description: "RAG architecture, evaluation harnesses, governed deployment, agent boundaries, and LLM procurement  -  for teams taking AI from prototype to production.",
    icon: "◈",
  },
  {
    id: "cyber-soc",
    label: "Security & SOC Operations",
    description: "Detection engineering, SOC automation, evidence design, XDR cutover, and threat-informed defence  -  built for security teams that write runbooks, not slide decks.",
    icon: "◉",
  },
  {
    id: "data-search",
    label: "Data & Search Infrastructure",
    description: "Medallion architecture, streaming pipelines, OpenSearch migrations, real-time analytics, and KYC/ML operational discipline  -  for platform and data engineering leads.",
    icon: "◎",
  },
  {
    id: "playbooks",
    label: "Engineering Playbooks",
    description: "Cutover plans, SLA frameworks, bid writing strategy, observability design, and evaluation ownership  -  practical references for technical buyers and delivery leads.",
    icon: "◇",
  },
] as const;

/** Editorial bridge  -  "What we are tracking" */
export const BLOG_SIGNAL_BLOCK = {
  eyebrow: "Signals we are watching",
  title: "What shapes this research.",
  items: [
    {
      signal: "AI-mediated discovery",
      note: "ChatGPT, Perplexity, and Google AI Overviews are absorbing queries that once went to blue links. Brand visibility now requires structured, retrievable content.",
    },
    {
      signal: "Production AI governance pressure",
      note: "Legal and security teams are blocking AI rollouts at the gate. The blocker is not capability  -  it is audit trails, PII controls, and rollback criteria.",
    },
    {
      signal: "Search infrastructure at scale",
      note: "OpenSearch migrations continue to accelerate. The failure mode is not tooling  -  it is cutover discipline, relevance validation, and operational handover.",
    },
    {
      signal: "SOC evidence decay",
      note: "Automation without documented evidence creates audit exposure. The gap between 'we automated it' and 'here is the audit trail' is widening.",
    },
  ],
} as const;

/** 12-month × 4 articles content calendar (May 2026 → April 2027) */
export type ContentCalendarArticle = {
  readonly month: string;
  readonly title: string;
  readonly targetKeyword: string;
  readonly searchIntent: "informational" | "commercial" | "navigational";
  readonly angle: string;
  readonly expectedValue: string;
  readonly category: string;
};

export type ContentCalendarMonth = {
  readonly month: string;
  readonly theme: string;
  readonly articles: readonly ContentCalendarArticle[];
};

export const CONTENT_CALENDAR: readonly ContentCalendarMonth[] = [
  {
    month: "May 2026",
    theme: "AI Search Foundations",
    articles: [
      {
        month: "May 2026",
        title: "AEO Checklist: 20 Structural Changes for Featured Snippet Capture",
        targetKeyword: "answer engine optimisation checklist",
        searchIntent: "informational",
        angle: "Actionable, numbered checklist  -  no fluff, directly implementable by in-house teams",
        expectedValue: "High organic + GEO value: checklist format is heavily retrieved in AI answers",
        category: "ai-llm",
      },
      {
        month: "May 2026",
        title: "Core Web Vitals 2026: What Changed and What Still Matters",
        targetKeyword: "core web vitals 2026 updates",
        searchIntent: "informational",
        angle: "Annual update article covering INP as the new FID, updated field data methodology",
        expectedValue: "Strong seasonal search volume; positions AiRAT as technical SEO authority",
        category: "playbooks",
      },
      {
        month: "May 2026",
        title: "RAG vs Fine-Tuning: The Decision Framework for Enterprise AI",
        targetKeyword: "RAG vs fine-tuning enterprise decision",
        searchIntent: "commercial",
        angle: "Decision tree format with cost, latency, and governance trade-offs  -  not opinion",
        expectedValue: "High commercial intent; decision-maker audience; links to AI services page",
        category: "ai-llm",
      },
      {
        month: "May 2026",
        title: "SOC Metrics That Board Members Actually Understand",
        targetKeyword: "SOC metrics board presentation",
        searchIntent: "informational",
        angle: "Translates technical SOC KPIs into business language with example board slide language",
        expectedValue: "Niche but high-value audience (CISOs preparing board decks); strong AEO value",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "June 2026",
    theme: "Search Infrastructure",
    articles: [
      {
        month: "June 2026",
        title: "OpenSearch Index Design for High-Traffic Ecommerce: A Pattern Library",
        targetKeyword: "OpenSearch ecommerce index design",
        searchIntent: "informational",
        angle: "Concrete shard, replica, and mapping patterns from production deployments  -  not docs restatement",
        expectedValue: "Technical depth differentiator; links to data & search services and portfolio",
        category: "data-search",
      },
      {
        month: "June 2026",
        title: "Perplexity vs ChatGPT for Research: What Brand Managers Need to Know",
        targetKeyword: "Perplexity vs ChatGPT brand visibility",
        searchIntent: "informational",
        angle: "Comparison format optimised for AI retrieval; brand visibility angle rather than user experience",
        expectedValue: "High GEO retrieval potential; targets CMO and brand manager audience",
        category: "ai-llm",
      },
      {
        month: "June 2026",
        title: "JavaScript SEO in 2026: The Rendering Decisions That Cost Rankings",
        targetKeyword: "JavaScript SEO rendering decisions",
        searchIntent: "informational",
        angle: "Framework-specific rendering patterns  -  Next.js, Nuxt, Angular  -  and their crawl implications",
        expectedValue: "High-value technical SEO content; positions AiRAT in engineering-led SEO",
        category: "playbooks",
      },
      {
        month: "June 2026",
        title: "Data Lineage for Finance: What Auditors Check and How to Pass",
        targetKeyword: "data lineage audit financial services",
        searchIntent: "commercial",
        angle: "Audit-specific framing  -  what specific artefacts regulators request and how to produce them",
        expectedValue: "Targets regulated industry audience; strong conversion intent; links to data services",
        category: "data-search",
      },
    ],
  },
  {
    month: "July 2026",
    theme: "AI Governance",
    articles: [
      {
        month: "July 2026",
        title: "AI Governance Frameworks for UAE Enterprises: Comparing Approaches",
        targetKeyword: "AI governance framework UAE enterprise",
        searchIntent: "commercial",
        angle: "Region-specific analysis covering UAE NIST AI RMF, EU AI Act implications, and local regulatory guidance",
        expectedValue: "Strong geographic targeting for UAE market; high conversion intent; links to AI services",
        category: "ai-llm",
      },
      {
        month: "July 2026",
        title: "SIEM Architecture for Multi-Tenant Security Operations",
        targetKeyword: "SIEM architecture multi-tenant SOC",
        searchIntent: "informational",
        angle: "Technical architecture patterns for MSSP and in-house multi-tenant SIEM deployments",
        expectedValue: "High-value technical content; direct link to csoc case study",
        category: "cyber-soc",
      },
      {
        month: "July 2026",
        title: "The Structured Data Playbook: Schema Types That Actually Get Rich Results",
        targetKeyword: "structured data schema rich results playbook",
        searchIntent: "informational",
        angle: "Schema types ranked by rich result eligibility and implementation ROI  -  not just a types list",
        expectedValue: "Strong SEO topical authority; high AEO value for schema-related queries",
        category: "playbooks",
      },
      {
        month: "July 2026",
        title: "LLM Cost Control: Token Budgets, Caching, and Inference Optimisation",
        targetKeyword: "LLM cost control token budget optimisation",
        searchIntent: "commercial",
        angle: "FinOps angle for AI programmes  -  specific techniques with cost impact estimates",
        expectedValue: "High commercial intent from budget-conscious enterprise teams; links to AI gateway services",
        category: "ai-llm",
      },
    ],
  },
  {
    month: "August 2026",
    theme: "Conversion & Experience",
    articles: [
      {
        month: "August 2026",
        title: "SXO Audit: 15 Questions to Find Where Your Search Traffic Leaks",
        targetKeyword: "SXO search experience optimisation audit",
        searchIntent: "informational",
        angle: "Self-audit format with specific page-level checks tied to user behaviour signals",
        expectedValue: "Strong AEO value; positions AiRAT in SXO; links to SXO service page",
        category: "playbooks",
      },
      {
        month: "August 2026",
        title: "Internal Linking for Enterprise Sites: Architecture Over Instinct",
        targetKeyword: "internal linking strategy enterprise website",
        searchIntent: "informational",
        angle: "Systematic approach to internal link architecture  -  programmatic planning, not page-by-page guesswork",
        expectedValue: "High SEO topical authority value; complements technical SEO services content",
        category: "playbooks",
      },
      {
        month: "August 2026",
        title: "Vector Databases Compared: Pinecone, Weaviate, Milvus for Enterprise RAG",
        targetKeyword: "vector database comparison enterprise RAG",
        searchIntent: "commercial",
        angle: "Production performance, operational overhead, and cost comparison  -  not synthetic benchmarks",
        expectedValue: "High commercial intent; strong AI-system authority signal; links to AI services",
        category: "ai-llm",
      },
      {
        month: "August 2026",
        title: "Threat Intelligence for Non-Technical Boards: A Communication Framework",
        targetKeyword: "threat intelligence board communication CISO",
        searchIntent: "informational",
        angle: "Translating threat intel into board-appropriate risk language  -  frameworks and example language",
        expectedValue: "Niche high-value CISO audience; strong AEO retrieval for board presentation queries",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "September 2026",
    theme: "Enterprise AI Deployment",
    articles: [
      {
        month: "September 2026",
        title: "Deploying RAG in Regulated Environments: Compliance Checklist",
        targetKeyword: "RAG deployment regulated industry compliance",
        searchIntent: "commercial",
        angle: "Compliance-first RAG deployment checklist covering data residency, audit trails, and explainability",
        expectedValue: "High commercial intent from regulated industry buyers; strong conversion path to AI services",
        category: "ai-llm",
      },
      {
        month: "September 2026",
        title: "Search Performance for Retail: The Technical Metrics That Drive Revenue",
        targetKeyword: "search performance retail ecommerce revenue",
        searchIntent: "commercial",
        angle: "Maps search technical metrics (latency, recall, freshness) to revenue impact in retail context",
        expectedValue: "Strong vertical authority; links to ecommerce search case studies in portfolio",
        category: "data-search",
      },
      {
        month: "September 2026",
        title: "Page Speed and Revenue: What the Research Actually Shows",
        targetKeyword: "page speed revenue impact research",
        searchIntent: "informational",
        angle: "Synthesises Deloitte, Google, and Portent research on speed-to-revenue relationships",
        expectedValue: "Research synthesis format gets high AEO/GEO retrieval; links to technical SEO services",
        category: "playbooks",
      },
      {
        month: "September 2026",
        title: "Zero-Trust Architecture for AI APIs: Why Perimeter Is Not Enough",
        targetKeyword: "zero trust architecture AI API security",
        searchIntent: "informational",
        angle: "Applies zero-trust principles specifically to LLM API access control  -  concrete implementation patterns",
        expectedValue: "Bridges cybersecurity and AI audiences; links to both service domains",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "October 2026",
    theme: "Data & Search Architecture",
    articles: [
      {
        month: "October 2026",
        title: "dbt in Production: Testing Patterns for Finance-Grade Data",
        targetKeyword: "dbt production testing finance data quality",
        searchIntent: "informational",
        angle: "Specific dbt test patterns for regulated financial data  -  audit-ready testing approach",
        expectedValue: "Technical depth; targets data engineers in financial services; links to data services",
        category: "data-search",
      },
      {
        month: "October 2026",
        title: "AI Overviews: The Complete Technical Guide for SEOs",
        targetKeyword: "Google AI Overviews technical SEO guide",
        searchIntent: "informational",
        angle: "Technical implementation guide  -  schema, structure, E-E-A-T signals  -  not conceptual overview",
        expectedValue: "Strong search volume; high GEO value; links to AEO/GEO services page",
        category: "ai-llm",
      },
      {
        month: "October 2026",
        title: "Multi-Region OpenSearch: Replication, Failover, and Consistency Trade-Offs",
        targetKeyword: "OpenSearch multi-region replication failover",
        searchIntent: "informational",
        angle: "Architecture patterns with explicit consistency trade-offs  -  not idealised diagrams",
        expectedValue: "High technical authority value; targets senior platform engineers",
        category: "data-search",
      },
      {
        month: "October 2026",
        title: "Building a Detection-as-Code Programme: Tools, Process, and Culture",
        targetKeyword: "detection as code SOC programme",
        searchIntent: "informational",
        angle: "End-to-end detection engineering programme design  -  team structure, tooling, governance",
        expectedValue: "Strong topical authority in detection engineering; links to cybersecurity services",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "November 2026",
    theme: "AI Visibility at Scale",
    articles: [
      {
        month: "November 2026",
        title: "Brand Monitoring in the Age of AI: What to Track Beyond Social",
        targetKeyword: "brand monitoring AI search visibility",
        searchIntent: "commercial",
        angle: "Extends traditional brand monitoring to AI platforms  -  tools, sampling methodology, reporting",
        expectedValue: "Bridges marketing and AI audience; links to AI Visibility services",
        category: "ai-llm",
      },
      {
        month: "November 2026",
        title: "Schema Markup That Actually Earns Rich Results: A 2026 Audit",
        targetKeyword: "schema markup rich results 2026",
        searchIntent: "informational",
        angle: "Annual audit of which schema types are earning rich results vs being ignored  -  data-backed",
        expectedValue: "High seasonal search volume; strong AEO value; links to technical SEO services",
        category: "playbooks",
      },
      {
        month: "November 2026",
        title: "Kafka at Scale: Partitioning, Retention, and Operational Debt",
        targetKeyword: "Kafka partitioning retention production scale",
        searchIntent: "informational",
        angle: "Production operations perspective  -  what breaks at scale and how to design around it",
        expectedValue: "Technical authority; targets senior data engineers; links to data infrastructure services",
        category: "data-search",
      },
      {
        month: "November 2026",
        title: "AI in SIEM: What Works, What Doesn't, and What to Buy vs Build",
        targetKeyword: "AI in SIEM buy vs build",
        searchIntent: "commercial",
        angle: "Procurement-framed analysis of ML/AI capabilities in SIEM platforms  -  when vendor beats custom",
        expectedValue: "High commercial intent from SIEM buyers; links to cybersecurity services and case studies",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "December 2026",
    theme: "Year-End Reviews & Predictions",
    articles: [
      {
        month: "December 2026",
        title: "AI Search in 2026: What Actually Changed and What It Means for 2027",
        targetKeyword: "AI search changes 2026 year review",
        searchIntent: "informational",
        angle: "Data-backed annual review of AI search behaviour shifts  -  not opinion, specific metrics",
        expectedValue: "High seasonal search; strong GEO value as AI systems retrieve year-in-review content",
        category: "ai-llm",
      },
      {
        month: "December 2026",
        title: "Enterprise SEO in 2027: The Technical Priorities That Will Drive Rankings",
        targetKeyword: "enterprise SEO 2027 technical priorities",
        searchIntent: "informational",
        angle: "Forward-looking but grounded in current trajectory  -  concrete predictions with rationale",
        expectedValue: "Strong year-end + New Year search volume; positions AiRAT as SEO authority",
        category: "playbooks",
      },
      {
        month: "December 2026",
        title: "The Data Platform Checklist for 2027 Audit Readiness",
        targetKeyword: "data platform audit readiness checklist 2027",
        searchIntent: "commercial",
        angle: "Year-end audit preparation checklist  -  what regulated enterprises should have in place",
        expectedValue: "High commercial intent; strong seasonal relevance; links to data services",
        category: "data-search",
      },
      {
        month: "December 2026",
        title: "SOC Maturity Assessment: Where Does Your Team Stand?",
        targetKeyword: "SOC maturity assessment framework",
        searchIntent: "informational",
        angle: "Self-assessment framework against SOC maturity model  -  drives engagement and qualification",
        expectedValue: "High-value lead generation asset; links to cybersecurity services and strategy call",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "January 2027",
    theme: "New Year, New Stack",
    articles: [
      {
        month: "January 2027",
        title: "What Is Agentic AI? A Technical Definition for Enterprise Buyers",
        targetKeyword: "agentic AI definition enterprise buyers",
        searchIntent: "informational",
        angle: "Clear technical definition with procurement implications  -  not hype, not oversimplification",
        expectedValue: "High AEO value for definitional queries; positions AiRAT in emerging AI category",
        category: "ai-llm",
      },
      {
        month: "January 2027",
        title: "GEO Measurement: How to Track Brand Visibility in AI Search",
        targetKeyword: "GEO measurement AI brand visibility tracking",
        searchIntent: "informational",
        angle: "Practical measurement guide  -  sampling methodology, tools, and reporting templates",
        expectedValue: "High practical value; strong GEO retrieval potential for measurement queries",
        category: "ai-llm",
      },
      {
        month: "January 2027",
        title: "OpenSearch Pricing: What It Costs to Run at Scale (With Real Numbers)",
        targetKeyword: "OpenSearch pricing costs at scale",
        searchIntent: "commercial",
        angle: "Honest cost modelling for different scale points  -  self-managed vs Amazon OpenSearch Service",
        expectedValue: "High commercial intent; buyers at cost evaluation stage are close to decision",
        category: "data-search",
      },
      {
        month: "January 2027",
        title: "Security Architecture for AI Systems: A Framework for CISOs",
        targetKeyword: "AI system security architecture CISO framework",
        searchIntent: "commercial",
        angle: "Bridges security and AI  -  threat model, access control, logging, and governance for AI deployments",
        expectedValue: "Bridges both service domains; high-value CISO audience; strong conversion intent",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "February 2027",
    theme: "Search Experience Research",
    articles: [
      {
        month: "February 2027",
        title: "What Bounce Rate Actually Tells You (And What It Doesn't)",
        targetKeyword: "bounce rate interpretation SEO impact",
        searchIntent: "informational",
        angle: "Evidence-based clarification of bounce rate's SEO significance after GA4 migration",
        expectedValue: "High search volume; positions AiRAT in SXO + analytics authority",
        category: "playbooks",
      },
      {
        month: "February 2027",
        title: "Perplexity Pro for Enterprise Research: A Practitioner's Guide",
        targetKeyword: "Perplexity Pro enterprise research guide",
        searchIntent: "informational",
        angle: "Practical usage guide for enterprise research teams  -  workflows, limitations, and citation verification",
        expectedValue: "Growing search volume; strong GEO value; content type LLMs retrieve frequently",
        category: "ai-llm",
      },
      {
        month: "February 2027",
        title: "Delta Lake vs Apache Iceberg: The Governance and Ecosystem Reality",
        targetKeyword: "Delta Lake vs Apache Iceberg governance comparison",
        searchIntent: "commercial",
        angle: "Vendor-neutral comparison with governance and operational overhead as primary axes",
        expectedValue: "High technical authority; data architecture decision-maker audience",
        category: "data-search",
      },
      {
        month: "February 2027",
        title: "Alert Fatigue: How to Measure It, Reduce It, and Keep It Reduced",
        targetKeyword: "alert fatigue measurement reduction SOC",
        searchIntent: "informational",
        angle: "Specific metrics and reduction playbook  -  not generic 'reduce noise' advice",
        expectedValue: "High-value SOC audience; strong AEO retrieval potential; links to cybersecurity services",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "March 2027",
    theme: "Enterprise AI at Depth",
    articles: [
      {
        month: "March 2027",
        title: "LLM Agent Security: Attack Vectors and Defence Patterns",
        targetKeyword: "LLM agent security attack vectors defence",
        searchIntent: "informational",
        angle: "Technical security analysis of agent architectures  -  prompt injection, tool misuse, data exfiltration",
        expectedValue: "Emerging high-value topic; bridges security and AI audiences; strong topical authority",
        category: "ai-llm",
      },
      {
        month: "March 2027",
        title: "Technical Content for Engineers: The SEO Playbook That Actually Works",
        targetKeyword: "technical content SEO engineers developers",
        searchIntent: "informational",
        angle: "Content strategy for companies selling to developers  -  what ranks, what gets cited in AI, what converts",
        expectedValue: "Strong GEO retrieval for developer marketing queries; links to SXO and GEO services",
        category: "playbooks",
      },
      {
        month: "March 2027",
        title: "Data Mesh Implementation: Where It Works and Where It Fails",
        targetKeyword: "data mesh implementation success failure patterns",
        searchIntent: "informational",
        angle: "Honest pattern analysis  -  specific organisational conditions where data mesh adds vs subtracts value",
        expectedValue: "High authority signal; targets senior data leaders; links to data architecture services",
        category: "data-search",
      },
      {
        month: "March 2027",
        title: "Building an Evidence-First SOC: Architecture Decisions That Last",
        targetKeyword: "evidence-first SOC architecture long term",
        searchIntent: "informational",
        angle: "SOC architecture patterns optimised for evidence preservation and audit  -  beyond detection and response",
        expectedValue: "Topical authority in SOC engineering; links to csoc case study and cybersecurity services",
        category: "cyber-soc",
      },
    ],
  },
  {
    month: "April 2027",
    theme: "Visibility Intelligence Annual",
    articles: [
      {
        month: "April 2027",
        title: "One Year of GEO: What the Data Shows About AI Search Optimisation",
        targetKeyword: "GEO results data AI search optimisation one year",
        searchIntent: "informational",
        angle: "First-party data and industry research synthesis on GEO programme performance metrics",
        expectedValue: "Authoritative anchor content for GEO cluster; high citation potential in AI systems",
        category: "ai-llm",
      },
      {
        month: "April 2027",
        title: "Enterprise Technical SEO ROI: How to Calculate and Present It",
        targetKeyword: "enterprise technical SEO ROI calculation",
        searchIntent: "commercial",
        angle: "Specific calculation methodology for technical SEO ROI  -  organic revenue attribution models",
        expectedValue: "High commercial intent from budget-holding stakeholders; links to technical SEO services",
        category: "playbooks",
      },
      {
        month: "April 2027",
        title: "The Complete Guide to Streaming Data Quality for Regulated Industries",
        targetKeyword: "streaming data quality regulated industry guide",
        searchIntent: "commercial",
        angle: "Comprehensive guide to real-time data quality in financial services, healthcare, and government",
        expectedValue: "Flagship long-form content for data cluster; high conversion intent; links to data services",
        category: "data-search",
      },
      {
        month: "April 2027",
        title: "Cyber Threat Intelligence: Building a Programme From Zero",
        targetKeyword: "cyber threat intelligence programme from zero",
        searchIntent: "commercial",
        angle: "Zero-to-one guide for organisations starting a CTI function  -  process, tooling, and output types",
        expectedValue: "High commercial intent from security leaders; links to detection engineering services",
        category: "cyber-soc",
      },
    ],
  },
] as const;
